### ISSUE TITLE
validators appear in the wrong networks

### ISSUE THREAD

**Issue by ckniffen** [ripple/validator-history-service#190]
When calling https://data.xrpl.org/v1/network/validators/xahau-main all `main` and `xahau-main` validators are included.

When running locally this problem does not exist.  Looking at the data returned the validators have the correct `networks` and `chain` fields.

**Comment by bigcjat** [comment]
Running locally, this does happen for me. Sometimes will show up as Chain.5
Also, for some reason my VHS is collecting validators from every network, but I expected it to only find xahau validators. Filtering by network will have a mix of the network you specified and randomly other validators as well.

**Comment by mvadari** [comment]
Why would you expect the VHS to only find Xahau validators? Did you edit the list of networks? 

That might be because some peers stick around for a bit when a validator switches networks.

**Comment by bigcjat** [comment]
> Why would you expect the VHS to only find Xahau validators? Did you edit the list of networks?
> 
> That might be because some peers stick around for a bit when a validator switches networks.

Yes, my config is set to only xahau

export MAINNET_P2P_ENTRY= (my endpoint on xahau)

export MAINNET_UNL=vl.xahau.org

export RIPPLED_RPC_ADMIN=(my endpoint on xahau)

**Comment by mvadari** [comment]
> > Why would you expect the VHS to only find Xahau validators? Did you edit the list of networks?
> > That might be because some peers stick around for a bit when a validator switches networks.
> 
> Yes, my config is set to only xahau
> 
> export MAINNET_P2P_ENTRY= (my endpoint on xahau)
> 
> export MAINNET_UNL=vl.xahau.org
> 
> export RIPPLED_RPC_ADMIN=(my endpoint on xahau)

That's not the only place network data is stored. The main data is here: https://github.com/ripple/validator-history-service/blob/main/src/shared/database/networks.ts

The way that you're trying to just get Xahau data probably doesn't work properly with the UNLs.

**Comment by bigcjat** [comment]
Awesome, thank you!

**Comment by mvadari** [comment]
Closing because this issue seems resolved. Feel free to reopen if you continue to run into this issue.
