### ISSUE TITLE
lookup validators by public/signing key and master_key

### ISSUE THREAD

**Issue by ckniffen** [ripple/validator-history-service#79]
Currently we only lookup in the database by master_key but often that is hidden by validators.  If the validator is in the cache we can find it by public key which is strange.

This file needs to be updated.
https://github.com/ripple/validator-history-service/blob/main/src/api/routes/v1/validator.ts#L195

**Comment by ckniffen** [comment]
I'm a fool.

**Comment by DOPEBOSS1** [comment]
Getting my coin
